USE CHALLENGE_BACKEND_ALURAFLIX;

CREATE TABLE USUARIOS(
	IdUsuario NVARCHAR(400) NOT NULL PRIMARY KEY,
    EmailUsuario NVARCHAR(256) NOT NULL UNIQUE KEY,
    NomeUsuario NVARCHAR(100) NOT NULL,
    SobrenomeUsuario NVARCHAR(100) NOT NULL,
    SenhaUsuario NVARCHAR(100) NOT NULL
);