USE CHALLENGE_BACKEND_ALURAFLIX;

CREATE TABLE FAVORITOS(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    IdVideo INT NOT NULL,
    IdUsuario VARCHAR(255) NOT NULL,
    FOREIGN KEY (IdVideo) REFERENCES VIDEO(IdVideo),
    FOREIGN KEY (IdUsuario) REFERENCES ASPNETUSERS(Id)
);